version: '3.8'

services:
  shell:
    build:
      context: .
    image: usf
    hostname: usf-shell
    volumes:
      - ./usf:/app/usf
      - ./tests:/app/tests
      - ./Makefile:/app/Makefile
      - ./.importlinter:/app/.importlinter

  django:
    image: usf
    hostname: usf-django
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      unleash:
        condition: service_healthy
    volumes:
      - ./usf:/app/usf
      - ./tests:/app/tests
    command: make run

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli --raw incr ping
      start_period: 1s
      interval: 1s
      timeout: 30s
      retries: 5

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=usf
      - POSTGRES_USER=usf
      - POSTGRES_PASSWORD=usf
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d usf -U usf
      start_period: 1s
      interval: 1s
      timeout: 30s
      retries: 5

  unleash:
    image: unleashorg/unleash-server:6
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: usf
      DATABASE_USERNAME: usf
      DATABASE_PASSWORD: usf
      DATABASE_SSL: false
      UNLEASH_DEFAULT_ADMIN_USERNAME: usf
      UNLEASH_DEFAULT_ADMIN_PASSWORD: usf
    ports:
      - "4242:4242"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      start_period: 1s
      interval: 1s
      timeout: 60s
      retries: 15
