# Generated by Django 5.1.5 on 2025-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAvailabilityModel",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("reserved_for", models.IntegerField(blank=True, null=True)),
                ("reserved_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
