# Generated by Django 5.1.5 on 2025-02-01 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productavailabilitymodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productavailabilitymodel",
            name="product_id",
        ),
        migrations.AddField(
            model_name="productavailabilitymodel",
            name="product",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productavailabilitymodel",
            name="reserved_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
