# Generated by Django 5.1.5 on 2026-01-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when_created", models.DateField(auto_created=True)),
                ("task_name", models.CharField()),
                ("arguments", models.JSONField()),
            ],
        ),
    ]
