# Generated by Django 5.1.5 on 2026-01-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxentry',
            name='when_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
