# Generated by Django 5.1.5 on 2025-02-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="product_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
